import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import App from "./components/LoadingScreen"; // Updated import
import { Inter } from 'next/font/google'
import { Playfair_Display } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mpilo - Portfolio",
  description: "Generated by create next app",
};

// Inter font
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], // heavier weights give you that "Display" feel
  variable: '--font-inter',
})

//Playfair font
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
  variable: '--font-playfair',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${playfair.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
      >
        <App>
          {children}
        </App>
      </body>
    </html>
  );
}